name: Draft a new release

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      releases: write

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}